import {app} from 'electron';import{mkdir,readFile,writeFile}from'node:fs/promises';import{join}from'node:path';import{spawn}from'node:child_process';import{runGit,tryGit}from'./git/exec';
export interface TaskDef{id:string;label:string;command:string;args:string[]}export interface TestResult{sha:string;task:string;ok:boolean;output:string;at:number}export interface Capsule{id:string;name:string;branch?:string;commit?:string;tabs:string[];active?:string|null;terminalOpen:boolean;note:string;at:number}
const dataFile=(n:string)=>join(app.getPath('userData'),n);async function json<T>(n:string,f:T):Promise<T>{try{return JSON.parse(await readFile(dataFile(n),'utf8'))as T}catch{return f}}async function save(n:string,v:unknown){await mkdir(app.getPath('userData'),{recursive:true});await writeFile(dataFile(n),JSON.stringify(v,null,2),{mode:0o600})}
export async function trustStatus(repo:string){return(await json<string[]>('trusted-repos.json',[])).includes(repo)}export async function setTrust(repo:string,v:boolean){const a=await json<string[]>('trusted-repos.json',[]);await save('trusted-repos.json',v?[...new Set([...a,repo])]:a.filter(x=>x!==repo));return v}
export async function tasks(repo:string):Promise<TaskDef[]>{const out:TaskDef[]=[];try{const p=JSON.parse(await readFile(join(repo,'package.json'),'utf8'))as{scripts?:Record<string,string>};for(const n of Object.keys(p.scripts??{}))out.push({id:`npm:${n}`,label:`npm · ${n}`,command:'npm',args:['run',n]})}catch{}const exists=(f:string)=>readFile(join(repo,f),'utf8').then(()=>true).catch(()=>false);if(await exists('Cargo.toml'))out.push({id:'cargo:test',label:'Cargo test',command:'cargo',args:['test']});if(await exists('pyproject.toml'))out.push({id:'pytest',label:'Pytest',command:'python',args:['-m','pytest']});if(await exists('go.mod'))out.push({id:'go:test',label:'Go test',command:'go',args:['test','./...']});return out}
function processRun(repo:string,c:string,args:string[]):Promise<{code:number;output:string}>{return new Promise((resolve,reject)=>{const p=spawn(c,args,{cwd:repo,env:{...process.env,CI:'1'},shell:false});let o='';p.stdout.on('data',d=>o+=d);p.stderr.on('data',d=>o+=d);p.on('error',reject);p.on('close',code=>resolve({code:code??-1,output:o.slice(-50000)}))})}
export async function runTask(repo:string,t:TaskDef):Promise<TestResult>{if(!await trustStatus(repo))throw new Error('Trust this repository before running tasks');const allowed=(await tasks(repo)).find(x=>x.id===t.id);if(!allowed)throw new Error('Unknown task');const r=await processRun(repo,allowed.command,allowed.args),sha=(await runGit(repo,['rev-parse','HEAD'])).trim(),item={sha,task:allowed.label,ok:r.code===0,output:r.output,at:Date.now()},all=await json<TestResult[]>('test-results.json',[]);await save('test-results.json',[item,...all].slice(0,200));return item}
export async function riskMap(repo:string){const raw=await runGit(repo,['log','--all','--max-count=200','--format=@@%H','--numstat']),result:Record<string,{files:number;churn:number;score:number;test?:'pass'|'fail'}>={};let h='';for(const l of raw.split('\n')){if(l.startsWith('@@')){h=l.slice(2);result[h]={files:0,churn:0,score:0};continue}const m=l.match(/^(\d+|-)\s+(\d+|-)\s+/);if(h&&m){result[h].files++;result[h].churn+=(m[1]==='-'?20:+m[1])+(m[2]==='-'?20:+m[2])}}const tests=await json<TestResult[]>('test-results.json',[]);for(const[k,v]of Object.entries(result)){v.score=Math.min(100,Math.round(Math.log2(1+v.churn)*12+v.files*2));const t=tests.find(x=>x.sha===k);if(t)v.test=t.ok?'pass':'fail'}return result}
export async function secretScan(repo:string){const diff=await runGit(repo,['diff','--cached','--no-color']),findings:{kind:string;line:string}[]=[];const ps:[string,RegExp][]=[['Private key',/BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY/],['GitHub token',/(github_pat_|ghp_)[A-Za-z0-9_]{20,}/],['Generic secret',/(api[_-]?key|secret|password)\s*[:=]\s*['"][^'"]{8,}/i],['AWS key',/AKIA[0-9A-Z]{16}/]];for(const l of diff.split('\n').filter(x=>x.startsWith('+')&&!x.startsWith('+++')))for(const[k,p]of ps)if(p.test(l))findings.push({kind:k,line:l.slice(1,180)});for(const n of(await runGit(repo,['diff','--cached','--name-only'])).split('\n').filter(Boolean))if(/(^|\/)(\.env($|\.)|id_rsa|id_ed25519|.*\.pem$)/i.test(n))findings.push({kind:'Sensitive filename',line:n});return findings}
export async function preview(repo:string,kind:'merge'|'rebase'|'reset',ref:string){await runGit(repo,['rev-parse','--verify',ref]);if(kind==='reset')return{kind,summary:((await runGit(repo,['log','--oneline',`${ref}..HEAD`]))+'\n'+(await runGit(repo,['diff','--stat',`${ref}..HEAD`]))).slice(0,30000)};if(kind==='rebase'){const base=(await runGit(repo,['merge-base','HEAD',ref])).trim();return{kind,summary:`Merge base: ${base.slice(0,10)}\nCommits to replay:\n${await runGit(repo,['log','--oneline',`${ref}..HEAD`])}`}}const base=(await runGit(repo,['merge-base','HEAD',ref])).trim(),tree=await tryGit(repo,['merge-tree',base,'HEAD',ref]),text=tree.stdout||tree.stderr;return{kind,summary:text.slice(0,30000),conflicts:/<<<<<<<|CONFLICT/.test(text)}}
export async function symbols(repo:string,w:string){if(!/^[A-Za-z_$][\w$]*$/.test(w))throw new Error('Select a valid symbol');const r=await tryGit(repo,['grep','-n','-w',w,'--','*.ts','*.tsx','*.js','*.jsx','*.py','*.rs','*.go']);return r.stdout.split('\n').filter(Boolean).slice(0,200).map(l=>{const[p,row,...text]=l.split(':');return{path:p,row:+row,text:text.join(':')}})}
export async function rename(repo:string,from:string,to:string){if(!await trustStatus(repo))throw new Error('Trust this repository before project-wide rename');if(!/^[A-Za-z_$][\w$]*$/.test(from)||!/^[A-Za-z_$][\w$]*$/.test(to))throw new Error('Invalid symbol');const matches=await symbols(repo,from),files=[...new Set(matches.map(x=>x.path))],re=new RegExp(`\\b${from.replace(/[$]/g,'\\$&')}\\b`,'g');for(const f of files){const p=join(repo,f),c=await readFile(p,'utf8');await writeFile(p,c.replace(re,to))}return{files:files.length,matches:matches.length}}
export async function capsules(repo:string){return(await json<Record<string,Capsule[]>>('capsules.json',{}))[repo]??[]}export async function saveCapsule(repo:string,c:Omit<Capsule,'id'|'at'>){const all=await json<Record<string,Capsule[]>>('capsules.json',{}),item={...c,id:`capsule-${Date.now()}`,at:Date.now()};all[repo]=[item,...(all[repo]??[])].slice(0,30);await save('capsules.json',all);return item}
